-- Videoteca Unifor — schema para Postgres self-hosted (EC2)
-- Substitui auth.users do Supabase por tabela local.

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS profiles (
    id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    full_name TEXT,
    role TEXT NOT NULL CHECK (role IN ('aluno', 'professor', 'funcionario', 'admin')) DEFAULT 'aluno',
    registration TEXT,
    course TEXT,
    phone TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS films (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    original_title TEXT,
    year INT,
    director TEXT,
    genre TEXT,
    duration TEXT,
    language TEXT,
    rating TEXT,
    media TEXT,
    cover TEXT,
    status TEXT NOT NULL DEFAULT 'available',
    location TEXT,
    synopsis TEXT,
    cast TEXT,
    subtitles TEXT,
    country TEXT,
    internal_code TEXT UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS copies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id BIGINT NOT NULL REFERENCES films(id) ON DELETE CASCADE,
    code TEXT NOT NULL UNIQUE,
    patrimonio TEXT,
    condition TEXT,
    status TEXT NOT NULL DEFAULT 'available',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES profiles(id),
    film_id BIGINT REFERENCES films(id),
    status TEXT NOT NULL DEFAULT 'waiting',
    requested_at TIMESTAMPTZ DEFAULT NOW(),
    pickup_until TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS loans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES profiles(id),
    copy_id BIGINT REFERENCES copies(id),
    borrowed_at TIMESTAMPTZ DEFAULT NOW(),
    due_at TIMESTAMPTZ,
    returned_at TIMESTAMPTZ,
    status TEXT NOT NULL DEFAULT 'borrowed'
);

CREATE TABLE IF NOT EXISTS rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    capacity INT,
    equipment TEXT[],
    status TEXT DEFAULT 'available'
);

CREATE TABLE IF NOT EXISTS room_bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id BIGINT REFERENCES rooms(id),
    professor_id UUID REFERENCES profiles(id),
    starts_at TIMESTAMPTZ NOT NULL,
    ends_at TIMESTAMPTZ NOT NULL,
    title TEXT,
    status TEXT DEFAULT 'confirmed'
);

CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    event_type TEXT,
    film_id BIGINT REFERENCES films(id),
    location TEXT,
    starts_at TIMESTAMPTZ,
    slots INT DEFAULT 0,
    enrolled INT DEFAULT 0,
    description TEXT,
    certificate BOOLEAN DEFAULT FALSE,
    status TEXT DEFAULT 'draft'
);

CREATE TABLE IF NOT EXISTS event_registrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT REFERENCES events(id) ON DELETE CASCADE,
    user_id UUID REFERENCES profiles(id),
    present BOOLEAN DEFAULT FALSE,
    UNIQUE (event_id, user_id)
);

CREATE TABLE IF NOT EXISTS professor_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    professor_id UUID REFERENCES profiles(id),
    request_type TEXT NOT NULL,
    payload JSONB,
    status TEXT NOT NULL DEFAULT 'analysis',
    staff_notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES profiles(id),
    title TEXT NOT NULL,
    body TEXT,
    read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS app_settings (
    id INT PRIMARY KEY DEFAULT 1 CHECK (id = 1),
    loan_days INT DEFAULT 7,
    max_items_per_user INT DEFAULT 3,
    max_reservations INT DEFAULT 2,
    reservation_pickup_days INT DEFAULT 3,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO app_settings (id) VALUES (1) ON CONFLICT DO NOTHING;
