-- Videoteca Unifor — schema inicial (Supabase / Postgres)
-- Execute no SQL Editor do Supabase ou via CLI de migrações.

create extension if not exists "uuid-ossp";

-- Perfis (1:1 com auth.users quando usar Supabase Auth)
create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  full_name text,
  role text not null check (role in ('aluno', 'professor', 'funcionario', 'admin')),
  registration text,
  course text,
  phone text,
  created_at timestamptz default now()
);

create table if not exists public.films (
  id bigint generated by default as identity primary key,
  title text not null,
  original_title text,
  year int,
  director text,
  genre text,
  duration text,
  language text,
  rating text,
  media text,
  cover text,
  status text not null default 'available',
  location text,
  synopsis text,
  cast text,
  subtitles text,
  country text,
  internal_code text unique,
  created_at timestamptz default now()
);

create table if not exists public.copies (
  id bigint generated by default as identity primary key,
  film_id bigint not null references public.films (id) on delete cascade,
  code text not null unique,
  patrimonio text,
  condition text,
  status text not null default 'available',
  created_at timestamptz default now()
);

create table if not exists public.reservations (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles (id),
  film_id bigint references public.films (id),
  status text not null default 'waiting',
  requested_at timestamptz default now(),
  pickup_until timestamptz
);

create table if not exists public.loans (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles (id),
  copy_id bigint references public.copies (id),
  borrowed_at timestamptz default now(),
  due_at timestamptz,
  returned_at timestamptz,
  status text not null default 'borrowed'
);

create table if not exists public.rooms (
  id bigint generated by default as identity primary key,
  name text not null,
  capacity int,
  equipment text[],
  status text default 'available'
);

create table if not exists public.room_bookings (
  id bigint generated by default as identity primary key,
  room_id bigint references public.rooms (id),
  professor_id uuid references public.profiles (id),
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  title text,
  status text default 'confirmed'
);

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  title text not null,
  event_type text,
  film_id bigint references public.films (id),
  location text,
  starts_at timestamptz,
  slots int default 0,
  enrolled int default 0,
  description text,
  certificate boolean default false,
  status text default 'draft'
);

create table if not exists public.event_registrations (
  id bigint generated by default as identity primary key,
  event_id bigint references public.events (id) on delete cascade,
  user_id uuid references public.profiles (id),
  present boolean default false,
  unique (event_id, user_id)
);

create table if not exists public.professor_requests (
  id bigint generated by default as identity primary key,
  professor_id uuid references public.profiles (id),
  request_type text not null,
  payload jsonb,
  status text not null default 'analysis',
  staff_notes text,
  created_at timestamptz default now()
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles (id),
  title text not null,
  body text,
  read boolean default false,
  created_at timestamptz default now()
);

create table if not exists public.app_settings (
  id int primary key default 1 check (id = 1),
  loan_days int default 7,
  max_items_per_user int default 3,
  max_reservations int default 2,
  reservation_pickup_days int default 3,
  updated_at timestamptz default now()
);

-- RLS (exemplo: habilitar e políticas mínimas; ajuste por perfil real)
alter table public.profiles enable row level security;
alter table public.films enable row level security;
alter table public.copies enable row level security;
alter table public.reservations enable row level security;
alter table public.loans enable row level security;
alter table public.rooms enable row level security;
alter table public.room_bookings enable row level security;
alter table public.events enable row level security;
alter table public.event_registrations enable row level security;
alter table public.professor_requests enable row level security;
alter table public.notifications enable row level security;
alter table public.app_settings enable row level security;

-- Leitura pública do catálogo (somente filmes publicados no acervo)
create policy "films_select_public" on public.films
  for select using (true);

create policy "profiles_self" on public.profiles
  for select using (auth.uid() = id);

create policy "profiles_self_update" on public.profiles
  for update using (auth.uid() = id);

-- Demais políticas: restringir insert/update a funcionários via service role no FastAPI
-- ou claims JWT customizados. Em produção, refine por role.

comment on table public.films is 'Catálogo audiovisual';
comment on table public.copies is 'Exemplares físicos/digital';
